# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Fast ridge regression solver
#' @description Solves the ridge regression problem using RcppArmadillo.
#' @param Z The predictor matrix.
#' @param X The response matrix.
#' @param lambda The regularization parameter.
#' @return The coefficient matrix.
#' @keywords internal
ridge_solve <- function(Z, X, lambda) {
    .Call(`_muscal_ridge_solve`, Z, X, lambda)
}

