# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

muscal_apply_row_system_cpp <- function(A_list, S) {
    .Call(`_muscal_muscal_apply_row_system_cpp`, A_list, S)
}

muscal_apply_row_operator_cpp <- function(A_list, S, graph_laplacian, graph_lambda, ridge) {
    .Call(`_muscal_muscal_apply_row_operator_cpp`, A_list, S, graph_laplacian, graph_lambda, ridge)
}

muscal_rowsum_counts_cpp <- function(X, idx, N) {
    .Call(`_muscal_muscal_rowsum_counts_cpp`, X, idx, N)
}

